// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGIds
{
        public const string leaderboard_best_scores = "CgkIqbWpsaoMEAIQAQ"; // <GPGSID>
        public const string achievement_pink_plane = "CgkIqbWpsaoMEAIQDw"; // <GPGSID>
        public const string achievement_red_plane = "CgkIqbWpsaoMEAIQEg"; // <GPGSID>
        public const string achievement_its_becoming_difficult = "CgkIqbWpsaoMEAIQCg"; // <GPGSID>
        public const string achievement_blue_plane = "CgkIqbWpsaoMEAIQDQ"; // <GPGSID>
        public const string achievement_sixty_rocks = "CgkIqbWpsaoMEAIQCA"; // <GPGSID>
        public const string achievement_grey_plane = "CgkIqbWpsaoMEAIQDg"; // <GPGSID>
        public const string achievement_youre_getting_better = "CgkIqbWpsaoMEAIQBA"; // <GPGSID>
        public const string achievement_best_pilot = "CgkIqbWpsaoMEAIQDA"; // <GPGSID>
        public const string achievement_purple_plane = "CgkIqbWpsaoMEAIQEA"; // <GPGSID>
        public const string achievement_thirty_rocks = "CgkIqbWpsaoMEAIQBQ"; // <GPGSID>
        public const string achievement_150k = "CgkIqbWpsaoMEAIQGA"; // <GPGSID>
        public const string achievement_forty_rocks = "CgkIqbWpsaoMEAIQBg"; // <GPGSID>
        public const string achievement_50k = "CgkIqbWpsaoMEAIQFw"; // <GPGSID>
        public const string achievement_30k = "CgkIqbWpsaoMEAIQFg"; // <GPGSID>
        public const string achievement_orange_plane = "CgkIqbWpsaoMEAIQEQ"; // <GPGSID>
        public const string achievement_were_having_fun = "CgkIqbWpsaoMEAIQBw"; // <GPGSID>
        public const string achievement_first_rocks = "CgkIqbWpsaoMEAIQAg"; // <GPGSID>
        public const string achievement_ten_rocks = "CgkIqbWpsaoMEAIQAw"; // <GPGSID>
        public const string achievement_ninety_rocks = "CgkIqbWpsaoMEAIQCw"; // <GPGSID>
        public const string achievement_seventy_rocks = "CgkIqbWpsaoMEAIQCQ"; // <GPGSID>
        public const string achievement_5k = "CgkIqbWpsaoMEAIQFA"; // <GPGSID>
        public const string achievement_10k = "CgkIqbWpsaoMEAIQFQ"; // <GPGSID>
        public const string achievement_yellow_plane = "CgkIqbWpsaoMEAIQEw"; // <GPGSID>

}

